### ISSUE TITLE
RJ45 Ethernet adapter to connect to SIYI A2 Mini

### ISSUE THREAD

**Issue by johan-rocha** [autonomous-drone-project/Siyi_A2_MINI#1]
# Description
This repository is focused on dispensing hm30 for direct connection to a companion computer

# Tasks
- [ ]  make physical connector adapter to rj45
- [ ]  make code to be sure that the ethernet connections are compatible according documentation
- [ ] create Gstreamer pipeline to connect to the camera
